services:
  mysql_database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: temp123
    ports:
      - "3307:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
    networks:
      - spring-mysql

  football_backend:
    build: ./football_backend_docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql_database
    networks:
      - spring-mysql

  football_frontend:
    build: ./football_frontend_docker
    ports:
      - "81:80"
    depends_on:
      - football_backend
    networks:
      - spring-mysql

volumes:
  mysql_volume:

networks:
  spring-mysql:
    driver: bridge